---
# config nfs services
- block:
  - name: installe nfs-common
    apt:
      name: nfs-common
      state: present
  - name: lockd & callback ports
    template:
      src: :etc:modprobe.d:nfs.conf.j2
      dest: /etc/modprobe.d/nfs.conf
      mode: '0600'
      owner: root
    notify: debian restart nfs all
  - name: statd port
    lineinfile:
      dest: /etc/default/nfs-common
      line: "{{ item }}"
    with_items:
      - 'STATDOPTS="-p {{ statd_port }}"'
      - 'NEED_STATD={% if nfsv4_only %}no{% else %}yes{% endif %}'
      - 'NEED_IDMAPD={% if nfsv4_enable %}yes{% else %}no{% endif %}'
    notify: debian restart nfs all
  - name: fix start-statd
    copy:
      src: :usr:sbin:start-statd
      dest: /usr/sbin/start-statd
      mode: '0755'
      owner: root
    when: not nfsv4_only
  - name: idmapd
    template:
      src: idmapd.conf.j2
      dest: /etc/idmapd.conf
      mode: '0644'
      owner: root
    notify: debian restart nfs all
    when: nfsv4_enable
  # https://www.kernel.org/doc/html/latest/filesystems/nfs/client-identifier.html
  - name: set nfs4.unique_id
    block:
      - name: is client unique id set ?
        command: 'grep "^[^#]*GRUB_CMDLINE_LINUX=.*nfs.nfs4_unique_id" /etc/default/grub'
        register: clientidset
        failed_when: False
        changed_when: False
        check_mode: False
      - name: fact grub nfs4_unique_id
        set_fact: 
          grub_nfs4_unique_id: '{% if clientidset.stdout_lines | count() > 0
                                %}{{ clientidset.stdout | regex_replace("^GRUB_CMDLINE_LINUX=.*nfs.nfs4_unique_id=(?P<nfsid>[a-fA-F0-9]+).*$","\g<nfsid>") }}{%
                                endif %}'
      - name: get kernel nfs4_unique_id
        command: 'cat /sys/module/nfs/parameters/nfs4_unique_id'
        register: clientid
        failed_when: False
        changed_when: False
        check_mode: False
      - name: get machine-id
        command: 'cat /etc/machine-id'
        check_mode: False
        changed_when: False
        register: machineid
      - name: fact nfs4_unique_id_valid
        set_fact:
          nfs4_unique_id_valid: '{{ machineid.stdout_lines[0] | truncate(32,True,"") }}'
      - name: get cmdline
        command: 'grep "^GRUB_CMDLINE_LINUX=" /etc/default/grub'
        register: grubcmdline
        changed_when: False
        check_mode: False
        failed_when: False
      - name: fact new grub cmdline
        set_fact:
          new_cmdline: '{{ grubcmdline.stdout | regex_replace(''GRUB_CMDLINE_LINUX=" ?'',"") | regex_replace('' ?"$'',"") |
                        regex_replace("nfs\.nfs4_unique_id=[a-zA-Z0-9]+","nfs.nfs4_unique_id="+nfs4_unique_id_valid) }}'
        when: grubcmdline.rc == 0 and grub_nfs4_unique_id is not match("^"+nfs4_unique_id_valid+"$")
      - name: set GRUB_CMDLINE_LINUX
        lineinfile:
          dest: /etc/default/grub
          line: 'GRUB_CMDLINE_LINUX="{{ new_cmdline }}"'
          regexp: '^GRUB_CMDLINE_LINUX=.*$'
        when: grubcmdline.rc == 0 and grub_nfs4_unique_id is not match("^"+nfs4_unique_id_valid+"$")
        notify: update-grub
      - name: set now
        shell: 'echo -n {{ nfs4_unique_id_valid }} > /sys/fs/nfs/net/nfs_client/identifier'
        when: clientid.rc == 0 and clientid.stdout is not match("^"+nfs4_unique_id_valid+"$")
  # automount LDAP
  - block:
    - name: autofs-ldap
      package:
        name: autofs-ldap
        state: present
    - name: install NFS/LDAP map
      template:
        src: autofs_ldap_auth.conf.j2
        dest: /etc/autofs_ldap_auth.conf
        mode: '0600'
    - name: use it
      lineinfile:
        dest: /etc/default/autofs
        line: '{{ item.k }}="{{ item.v }}"'
        regexp: '^{{ item.k }}='
        insertafter: '{{ item.k }}='
      with_items:
        - { k: AUTH_CONF_FILE, v: /etc/autofs_ldap_auth.conf }
        - { k: LDAP_URI, v: '{{ ldap_uri }}' }
        - { k: SEARCH_BASE, v: '{{ ldap_autofs_ou }}{{ ldap_base }}' }
      when: ansible_distribution_major_version | int < 12
      notify: debian autofs restart
    - name: use it (debian > 11)
      lineinfile:
        dest: /etc/autofs.conf
        line: '{{ item.key }} = {{ item.value }}'
        insertafter: '#{{ item.key }} =.*'
        regexp: '^{{ item.key }} ='
        state: '{% if item.value != "" %}present{% else %}absent{% endif %}'
      with_dict:
        mount_nfs_default_protocol: '{% if nfsv4_only %}4{% else %}3{% endif %}'
        ldap_uri: '"{{ ldap_uri }}"'
        browse_mode: 'no'
        ldap_timeout: '3'
        search_base: '{{ ldap_autofs_ou }}{{ ldap_base }}'
        auth_conf_file: '/etc/autofs_ldap_auth.conf'
      when: ansible_distribution_major_version | int > 11
      notify: debian autofs restart
    - name: enable automount in nsswitch.conf
      lineinfile:
        line: 'automount: files ldap'
        regexp: '^automount:'
        dest: /etc/nsswitch.conf
      when: ansible_distribution_major_version | int > 11
      notify: debian autofs restart
    when: ldap_autofs
